### ISSUE TITLE
Want option to get error , When no match pattern file on target host.

### ISSUE THREAD

**Issue by morihaya** [embulk/embulk-input-sftp#34]
When no file on path_match_pattern on target host , i want get error.
I think that it is correct to terminate normally even though the file does not exist on target host.
But in all cases it is not good to judge it as correct.
So it seems wonderful if there is an option to switch that judgment.

**Comment by sakama** [comment]
Hi.

It's possible to implement such feature in this plugin.
However, that might be related with Embulk grand design.
I don't know any plugin that raise `ConfigException` or other Exception when no file or record is found to load.

I think it's better to suggest to Embulk core to raise `ConfigException` when no file or record is found when Embulk execution.

**Comment by morihaya** [comment]
Hi sakama-san.

Thank you for your kind response.
You're right.
